print('this is first demo')
print('this is second demo')
print('this is three demo')
print('this is a fenzhi')
print('this is a fenzhi 2')
print('this is a fenzhi 3')
print('this is a fenzhi 4')
print('this is a hahaha')
print('this is a four demo')
print('this is a five demo')
print('this is a seven demo')
